import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import { getMessages } from "next-intl/server"; // Usamos getMessages para cargar los mensajes
import { NextIntlClientProvider } from "next-intl";
//import { useRouter } from "next/router";
import { getLocale } from "next-intl/server";

// Fuentes
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Obtener el idioma y las traducciones desde el servidor
  const locale = await getLocale();
  // const messages = await getMessages(locale); // Cargar los mensajes para el idioma actual

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
